[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/my-jalna"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/jalna-investment"
  to = "/industrial-summit"
  status = 301
  force = true

[[redirects]]
  from = "/jalna-investment/*"
  to = "/industrial-summit/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/investment"
  to = "/industrial-summit"
  status = 301
  force = true

[[redirects]]
  from = "/investment/*"
  to = "/industrial-summit/:splat"
  status = 301
  force = true
